#!/usr/bin/env node
// Regenerate the one-click sample the dashboard ships with.
//
// The dashboard has to be useful the moment someone opens it, including opened as a
// file on a laptop with no server and no records of their own — so a small set of
// records is inlined into the page rather than fetched. This produces that set from
// the same offline pipeline run the demo uses, so the sample is never a hand-written
// approximation of what the tool actually outputs.
//
//   node scripts/make-sample.mjs     regenerate, then run sync:core to inline it
//
// Every record it writes carries a fixture source, which is what makes the deck and
// the workbook mark them as illustrative. Do not hand-edit the output.

import { spawn } from 'node:child_process';
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(REPO_ROOT, 'pipeline/fixtures/sample-records.js');
const QUARTERS = ['Q4 FY25', 'Q1 FY26'];

function run(args, cwd) {
  return new Promise((done, fail) => {
    const child = spawn(process.execPath, [join(REPO_ROOT, 'pipeline/run.mjs'), ...args], { cwd, stdio: 'inherit' });
    child.on('error', fail);
    child.on('close', (code) => (code === 0 ? done() : fail(new Error(`pipeline/run.mjs exited ${code}`))));
  });
}

async function main() {
  const work = await mkdtemp(join(tmpdir(), 'tyre-sample-'));
  try {
    const records = [];
    for (const quarter of QUARTERS) {
      const out = join(work, `${quarter.replace(/\s+/g, '-').toLowerCase()}.json`);
      await run([`--quarter=${quarter}`, '--offline-extract', `--out=${out}`], REPO_ROOT);
      records.push(...JSON.parse(await readFile(out, 'utf8')).records);
    }

    const body = `/* ==== TYRE-SAMPLE:BEGIN ====
 * Sample records the dashboard can load with one click.
 *
 * Generated by scripts/make-sample.mjs from the synthetic fixtures in
 * pipeline/fixtures, and inlined into the dashboard by scripts/sync-core.mjs like the
 * other shared blocks. Do not hand-edit.
 *
 * Inlined rather than fetched because the dashboard has to work as a file on someone
 * else's laptop: opened straight from disk there is no server to fetch from, and a
 * demo that depends on finding a path is a demo that fails in front of people.
 *
 * Every record carries source: "fixture:..." — which is what makes the deck and the
 * workbook stamp them ILLUSTRATIVE. These are invented figures for real companies and
 * nothing downstream is allowed to forget it.
 */
var TYRE_SAMPLE_RECORDS = ${JSON.stringify(records)};
// The dashboard wraps its inlined blocks in an IIFE, so a bare \`var\` here is
// function-scoped and invisible to the rest of the page. Every other block exports
// itself the same way.
if (typeof window !== 'undefined') { window.TYRE_SAMPLE_RECORDS = TYRE_SAMPLE_RECORDS; }
if (typeof globalThis !== 'undefined') { globalThis.TYRE_SAMPLE_RECORDS = TYRE_SAMPLE_RECORDS; }
/* ==== TYRE-SAMPLE:END ==== */
`;
    await writeFile(OUT, body, 'utf8');
    process.stdout.write(`\n${OUT}\n  ${records.length} records across ${QUARTERS.length} quarters · ${(body.length / 1024).toFixed(0)} KB\n  Now run: npm run sync:core\n`);
    return 0;
  } finally {
    await rm(work, { recursive: true, force: true });
  }
}

const invokedDirectly = process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (invokedDirectly) {
  main().then(
    (code) => { process.exitCode = code; },
    (err) => { process.stderr.write(`${err.stack || err.message}\n`); process.exitCode = 1; }
  );
}

export { main };
